version = 1

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["react"]
  environment = [
    "nodejs",
    "cypress"
  ]

[[analyzers]]
name = "test-coverage"

[[transformers]]
name = "prettier"