version = 1

test_patterns = [
  "*.spec.ts",
  "*.spec.tsx",
  "*.spec.js",
  "*.spec.jsx",
  "tests/cypress/component/**/*.e2e.cy.tsx",
  "tests/cypress/pages/**/*.e2e.cy.js",
  "tests/cypress/integration/**/*.e2e.cy.tsx"
]

exclude_patterns = [
  "node_modules/*",
  ".next/*",
  "build/*",
  "dist/*"
]

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["react"]
  environment = [
    "jest",
    "cypress",
    "nodejs",
    "browser"
  ]

[[transformers]]
name = "prettier"

[[transformers]]
name = "standardjs"