version = 1

test_patterns = [
  "*.spec.ts",
  "*.spec.tsx",
  "*.spec.jsx",
  "tests/**",
  "*.int.cy.ts",
  "*.comp.cy.ts",
  "*.e2e.cy.ts"
]

exclude_patterns = [
  "node_modules/*",
  ".next/*",
  "public/*"
]

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["react"]
  environment = [
    "nodejs",
    "cypress"
  ]