import type { Metadata } from "next";
import { theme } from "theme";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "I'm WellluckY",
  description: "Generated by create next app",
  category: "Personal Website",
  themeColor: [
    { media: "(prefers-color-scheme: dark)", color: theme.color.neutral.black },
    {
      media: "(prefers-color-scheme: light)",
      color: theme.color.neutral.white,
    },
  ],
  applicationName: "I'm WellluckY",
  viewport: "width=device-width, initial-scale=1",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode,
}) {
  return (
    <html
      lang="pt-br"
      className={inter.className}
    >
      <body>{children}</body>
    </html>
  );
}
