import Document, { DocumentContext, DocumentInitialProps } from "next/document";
import { ServerStyleSheet } from "styled-components";
import { Metadata } from "next";
import { theme } from "theme";

export const metadata: Metadata = {
	title: { default: "I'm WellluckY", template: "%s | I'm WellluckY" },
	description: "Generated by create next app",
	category: "Personal Website",
	authors: [{ name: "Wellington Braga" }],
	manifest: "/manifest.json",
	robots: "/robots.txt",
	themeColor: [
		{ media: "(prefers-color-scheme: dark)", color: theme.color.neutral.black },
		{
			media: "(prefers-color-scheme: light)",
			color: theme.color.neutral.white,
		},
	],
	applicationName: "I'm Welllucky",
};

export default class MyDocument extends Document {
	static async getInitialProps(
		ctx: DocumentContext
	): Promise<DocumentInitialProps> {
		const sheet = new ServerStyleSheet();
		const originalRenderPage = ctx.renderPage;

		try {
			ctx.renderPage = () =>
				originalRenderPage({
					enhanceApp: (App) => (props) =>
						sheet.collectStyles(<App {...props} />),
				});

			const initialProps = await Document.getInitialProps(ctx);
			return {
				...initialProps,
				styles: (
					<>
						{initialProps.styles}
						{sheet.getStyleElement()}
					</>
				),
			};
		} finally {
			sheet.seal();
		}
	}
}
