import { Metadata } from "next";
import { theme } from "theme";
import HomePage from "./home";
import { Footer, Header } from "../../../../packages/components";
import { NavItemsProps } from "typing";
import { styled } from "styled-components";

export const metadata: Metadata = {
	title: { default: "I'm WellluckY", template: "%s | I'm WellluckY" },
	description: "Generated by create next app",
	category: "Personal Website",
	authors: [{ name: "Wellington Braga" }],
	manifest: "/manifest.json",
	robots: "/robots.txt",
	themeColor: [
		{
			media: "(prefers-color-scheme: dark)",
			color: theme.color.neutral.black,
		},
		{
			media: "(prefers-color-scheme: light)",
			color: theme.color.neutral.white,
		},
	],
	applicationName: "I'm Welllucky",
};

const navItems = [
	{
		title: "Quem sou eu",
		href: "/",
	},
	{
		title: "Conhecimentos",
		href: "/",
	},
	{
		title: "Projetos",
		href: "/",
	},
	{
		title: "Trabalhos",
		href: "/",
	},
	{
		title: "Entrar em contato",
		href: "/",
    isHighlight: true
	},
] as NavItemsProps[];

const ContentContainer = styled.div`
  display: flex;
  flex-direction: column;
  border: 2px green solid;
  width: 100%;
  height: max-content;
  flex-grow: 30;
  `;

const PageContainer = styled.div`
  display: flex;
  flex-direction: column;
  justify-content: space-between;
  border: 2px blue solid;
  width: 100vw;
  height: 100vh;
  `;

export default function Home() {
	return (
		<PageContainer>
			<Header
				logo="/l3.svg"
				navItems={navItems}
			/>
			<ContentContainer>
				<HomePage />
			</ContentContainer>
			<Footer />
		</PageContainer>
	);
}
